source "https://rubygems.org"
gem 'rails', '4.1.8'
gem 'bundler', '~> 1.3'
gem 'will_paginate'
gem 'airbrake', '~> 4.1.0'
gem "prawn", '0.12.0'
gem "mechanize", '2.5.1'
gem "andand"
gem 'by_star'
gem 'ar-configurator', '1.2.0', :require => 'configurator'
gem 'zendesk_api'
gem 'pg'
gem 'bcrypt'
gem 'authlogic'
gem 'daemons'
gem 'rgeo'
gem 'activerecord-postgis-adapter'
gem 'yaml_db'
gem 'koalas'
gem 'kangaroos'
gem 'carrierwave', '0.9.0'
gem 'fog', '1.25.0'
gem 'akami', :path => 'vendor/akami', :branch => 'certificate_signing'
gem 'savon', '1.2.0'
gem 'landata_vic', :git => 'https://ukswwUeTn718fR7rFtKa00RaPgvTDs5L:x-oauth-basic@bitbucket.org/pxadmin/landata_vic', :branch => 'master'
gem 'dav4rack', '0.2.10'
gem 'useragent'
gem 'lockfile'
gem 'humanizer'
gem 'money', '5.1.1'
gem 'postmark-mitt'
gem 'zip-zip'
gem 'rubyzip'
gem 'dynamic_form'
gem 'scout'
gem 'acl9', github: 'zachgraves/acl9', branch: 'master'
#gem 'textacular', '~> 3.0', require: 'textacular/rails' # required for plan surveyor link, atm not comp. with 4.5
gem 'request-log-analyzer'
gem 'hipchat'
gem 'jwt'
gem 'sidekiq'
gem 'sidekiq-status'
gem 'seed-fu'
gem 'intercom-rails'
gem 'intercom'
gem 'scout_statsd_rack'


######for sidekiq ui
gem 'sinatra', '>= 1.3.0', :require => nil
gem 'slim'
######
gem 'capistrano',  '~> 3.1'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano-maintenance', github: "capistrano/maintenance", require: false
gem 'capistrano-rvm'
gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
gem 'capistrano-passenger'
gem 'capistrano-bundler'
gem 'capistrano-rails-console'

gem 'uglifier'
gem 'sass'
gem 'iconv'
gem 'sidekiq-failures'
gem 'sidekiq-limit_fetch'
gem 'mobile-fu'

gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'
gem 'activerecord-deprecated_finders'
gem 'active_model_serializers'

# Re-enable when this is in the new version
# https://github.com/Nearsoft/rack-showme/pull/2
#group :development, :staging do
#  gem 'rack-showme'
#end

group :test do
  gem 'shoulda-matchers', require: false
  gem 'cucumber-rails', github: 'cucumber/cucumber-rails', branch: 'master_rails4_test'
end

group :development, :ci, :cucumber, :test do
  gem 'annotate'
  gem 'rspec-rails', '~> 2.14.2'
  gem 'email_spec'
  gem 'thin'
  gem 'faker'
  gem 'sham'
  gem 'machinist'
  gem 'database_cleaner'
  gem 'webrat'
  gem 'rack'
  gem 'launchy'
  gem 'awesome_print'
  gem 'nokogiri'
  gem 'parallel_tests'
  gem 'simplecov' , :require => false
  gem 'simplecov-json', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'ci_reporter_cucumber'
  gem 'ci_reporter_rspec'
  # Install phantomjs
  gem 'jasmine'
  gem 'jasminerice', :git => 'https://github.com/bradphelan/jasminerice.git'
  gem 'guard-jasmine'
  gem "poltergeist"
  gem "jasminerice-runner"
  gem 'webmock', '1.13.0'
  gem 'vcr'
  gem 'spring-commands-rspec'
  gem 'pry-rails'
  gem "brakeman", :require => false
end
